language: minimal
os: linux
dist: xenial

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - OS7=7.9.2009
    - OS7TAG=7.9.2009
  jobs:
    - BUILD_COMPOSE_FILE=docker-compose.yml       BUILD=centos7scm
    - BUILD_COMPOSE_FILE=docker-compose.yml       BUILD=stream8scm
    - BUILD_COMPOSE_FILE=docker-compose.web.yml   BUILD=centos7web
    - BUILD_COMPOSE_FILE=docker-compose.web.yml   BUILD=centos7uwsgi
    - BUILD_COMPOSE_FILE=docker-compose.web.yml   BUILD=stream8web
    - BUILD_COMPOSE_FILE=docker-compose.web.yml   BUILD=stream8httpd

script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} build --no-cache --pull ${BUILD}

after_success:
  - OS7TAG=7 OS8TAG=8 docker-compose -f ${BUILD_COMPOSE_FILE} build ${BUILD}

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  - provider: script
    script: docker-compose -f ${BUILD_COMPOSE_FILE} push ${BUILD}
  - provider: script
    script: OS7TAG=7 OS8TAG=8 docker-compose -f ${BUILD_COMPOSE_FILE} push ${BUILD}

jobs:
  include:
    - stage: base
      env:
        - BUILD_COMPOSE_FILE=docker-compose.yml
        - BUILD=centos7base
    - stage: base
      env:
        - BUILD_COMPOSE_FILE=docker-compose.yml
        - BUILD=stream8base
    - stage: scm
      env:
        - BUILD_COMPOSE_FILE=docker-compose.yml
        - BUILD=centos7jdk
    - stage: scm
      env:
        - BUILD_COMPOSE_FILE=docker-compose.yml
        - BUILD=stream8jdk
    - stage: scm
      env:
        - BUILD_COMPOSE_FILE=docker-compose.web.yml
        - BUILD=centos7node
    - stage: scm
      env:
        - BUILD_COMPOSE_FILE=docker-compose.dev.yml
        - BUILD=centos7systemd
    - stage: scm
      env:
        - BUILD_COMPOSE_FILE=docker-compose.dev.yml
        - BUILD=centos7webdev
    - stage: scm
      env:
        - BUILD_COMPOSE_FILE=docker-compose.web.yml
        - BUILD=stream8node
    - stage: scm
      env:
        - BUILD_COMPOSE_FILE=docker-compose.dev.yml
        - BUILD=stream8systemd
    - stage: scm
      env:
        - BUILD_COMPOSE_FILE=docker-compose.dev.yml
        - BUILD=stream8webdev
    - stage: dev
      env:
        - BUILD_COMPOSE_FILE=docker-compose.web.yml
        - BUILD=tomcat
    - stage: dev
      env:
        - BUILD_COMPOSE_FILE=docker-compose.dev.yml
        - BUILD=centos7nodedev
    - stage: dev
      env:
        - BUILD_COMPOSE_FILE=docker-compose.dev.yml
        - BUILD=stream8nodedev

stages:
  - base
  - test
  - scm
  - dev
