version: "3"
services:
  centos6curl:
    build:
      context: 6/curl
    image: aursu/centos:6.10-curl
  centos6scm:
    build:
      context: 6/scm
    image: aursu/centos:6.10-scm
  centos7base:
    build:
      context: 7/base
    image: aursu/centos:7.7.1908-base
  centos7scm:
    build:
      context: 7/scm
    image: aursu/centos:7.7.1908-scm
  centos7jdk:
    build:
      context: 7/openjdk/8
    image: aursu/centos:7.7.1908-jdk-8
  centos8base:
    build:
      context: 8/base
    image: aursu/centos:8.1.1911-base
  centos8scm:
    build:
      context: 8/scm
    image: aursu/centos:8.1.1911-scm
  centos8jdk:
    build:
      context: 8/openjdk/8
    image: aursu/centos:8.1.1911-jdk-8
