version: "3"
services:
  tomcat:
    build:
      context: 8-rocky/tomcat
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-tomcat"
  rocky8web:
    build:
      context: 8-rocky/web
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-web"
  rocky8httpd:
    build:
      context: 8-rocky/httpd
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-httpd"
  rocky8node18:
    build:
      context: 8-rocky/node18
      args:
        rocky: $RL8
    image: aursu/rockylinux:${RL8TAG}-node18
  rocky8node20:
    build:
      context: 8-rocky/node20
      args:
        rocky: $RL8
    image: aursu/rockylinux:${RL8TAG}-node20
  rocky8ruby31:
    build:
      context: 8-rocky/ruby31
      args:
        rocky: $RL8
    image: aursu/rockylinux:${RL8TAG}-ruby31
  stream9web:
    build:
      context: 9-stream/web
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-web"
  stream9httpd:
    build:
      context: 9-stream/httpd
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-httpd"
  stream9node18:
    build:
      context: 9-stream/node18
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-node18"
  stream9node20:
    build:
      context: 9-stream/node20
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-node20"