version: "3"
services:
  rocky8jdk:
    build:
      context: 8-rocky/openjdk/21
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-jdk-21"
  rocky8base:
    build:
      context: 8-rocky/base
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-base"
  rocky8scm:
    build:
      context: 8-rocky/scm
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-scm"
  stream9jdk:
    build:
      context: 9-stream/openjdk/22
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-jdk-22"
  stream9base:
    build:
      context: 9-stream/base
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-base"
  stream9scm:
    build:
      context: 9-stream/scm
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-scm"