version: "3"
services:
  centos6curl:
    build:
      context: 6/curl
      args:
        centos: $OS6
    image: "aursu/centos:${OS6}-curl"
  centos6scm:
    build:
      context: 6/scm
      args:
        centos: $OS6
    image: "aursu/centos:${OS6}-scm"
  centos7base:
    build:
      context: 7/base
      args:
        centos: $OS7
    image: "aursu/centos:${OS7}-base"
  centos7scm:
    build:
      context: 7/scm
      args:
        centos: $OS7
    image: "aursu/centos:${OS7}-scm"
  centos7jdk:
    build:
      context: 7/openjdk/8
      args:
        centos: $OS7
    image: "aursu/centos:${OS7}-jdk-8"
  centos8base:
    build:
      context: 8/base
      args:
        centos: $OS8
    image: "aursu/centos:${OS8}-base"
  centos8scm:
    build:
      context: 8/scm
      args:
        centos: $OS8
    image: "aursu/centos:${OS8}-scm"
  centos8jdk:
    build:
      context: 8/openjdk/8
      args:
        centos: $OS8
    image: "aursu/centos:${OS8}-jdk-8"
