version: "3"
services:
  centos7systemd:
    build:
      context: 7/systemd
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-systemd"
  centos7webdev:
    build:
      context: 7/web
      args:
        centos: $OS7
        image: scm
    image: "aursu/centos:${OS7TAG}-webdev"
  centos7node14dev:
    build:
      context: 7/node14/dev
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-node14dev"
  centos7node16dev:
    build:
      context: 7/node16/dev
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-node16dev"
  rocky8systemd:
    build:
      context: 8-rocky/systemd
      args:
        rocky: $RL8
    image: aursu/rockylinux:${RL8TAG}-systemd
  rocky8webdev:
    build:
      context: 8-rocky/web
      args:
        rocky: $RL8
        image: scm
    image: aursu/rockylinux:${RL8TAG}-webdev
  rocky8node16dev:
    build:
      args:
        rocky: $RL8
      context: 8-rocky/node16/dev
    image: aursu/rockylinux:${RL8TAG}-node16dev
  rocky8node18dev:
    build:
      args:
        rocky: $RL8
      context: 8-rocky/node18/dev
    image: aursu/rockylinux:${RL8TAG}-node18dev
  rocky8ruby31puppet:
    build:
      args:
        rocky: $RL8
      context: 8-rocky/ruby31/puppet
    image: aursu/rockylinux:${RL8TAG}-ruby31-puppet
  stream9systemd:
    build:
      context: 9-stream/systemd
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-systemd"
  stream9webdev:
    build:
      context: 9-stream/web
      args:
        centos: $OS9
        image: scm
    image: "aursu/centos:${OS9TAG}-webdev"
  stream9node16dev:
    build:
      args:
        centos: $OS9
      context: 9-stream/node16/dev
    image: "aursu/centos:${OS9TAG}-node16dev"
  stream9node18dev:
    build:
      args:
        centos: $OS9
      context: 9-stream/node18/dev
    image: "aursu/centos:${OS9TAG}-node18dev"
