version: "3"
services:
  tomcat:
    build:
      context: 7/tomcat
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-tomcat"
  centos7web:
    build:
      context: 7/web
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-web"
  centos7node:
    build:
      context: 7/node
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-node"
  centos7node16:
    build:
      context: 7/node-current
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-node16"
  stream8web:
    build:
      context: 8-stream/web
    image: aursu/centos:stream8-web
  stream8httpd:
    build:
      context: 8-stream/httpd
      args:
        centos: stream8
    image: aursu/centos:stream8-httpd
  stream8node:
    build:
      context: 8-stream/node
      args:
        centos: stream8
    image: aursu/centos:stream8-node16
  stream8node18:
    build:
      context: 8-stream/node-current
      args:
        centos: stream8
    image: aursu/centos:stream8-node18