version: "3"
services:
  curl:
    build:
      context: 6/curl
    image: centos:6-curl
  scm:
    build:
      context: 6/scm
    image: centos:6-scm
  httpd:
    build:
      context: httpd
    image: centos:httpd