version: "3"
services:
  centos7curl:
    build:
      context: 7/curl
    image: aursu/centos:7-curl
  centos7scm:
    build:
      context: 7/scm
    image: aursu/centos:7-scm
  centos7jdk:
    build:
      context: 7/openjdk/8
    image: aursu/centos:7-jdk-8
  tomcat:
    build:
      context: 7/tomcat
    image: aursu/centos:tomcat

