version: "3"
services:
  rocky8systemd:
    build:
      context: 8-rocky/systemd
      args:
        rocky: $RL8
    image: aursu/rockylinux:${RL8TAG}-systemd
  rocky8webdev:
    build:
      context: 8-rocky/web
      args:
        rocky: $RL8
        image: scm
    image: aursu/rockylinux:${RL8TAG}-webdev
  rocky8node18dev:
    build:
      args:
        rocky: $RL8
      context: 8-rocky/node18/dev
    image: aursu/rockylinux:${RL8TAG}-node18dev
  rocky8node20dev:
    build:
      args:
        rocky: $RL8
      context: 8-rocky/node20/dev
    image: aursu/rockylinux:${RL8TAG}-node20dev
  rocky8ruby31puppet:
    build:
      args:
        rocky: $RL8
      context: 8-rocky/ruby31/puppet
    image: aursu/rockylinux:${RL8TAG}-ruby31-puppet
  rocky8docker:
    build:
      context: 8-rocky/docker
      args:
        rocky: $RL8
    image: aursu/rockylinux:${RL8TAG}-docker-cli
  stream9systemd:
    build:
      context: 9-stream/systemd
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-systemd"
  stream9webdev:
    build:
      context: 9-stream/web
      args:
        centos: $OS9
        image: scm
    image: "aursu/centos:${OS9TAG}-webdev"
  stream9node18dev:
    build:
      args:
        centos: $OS9
      context: 9-stream/node18/dev
    image: "aursu/centos:${OS9TAG}-node18dev"
  stream9node20dev:
    build:
      args:
        centos: $OS9
      context: 9-stream/node20/dev
    image: "aursu/centos:${OS9TAG}-node20dev"