version: "3"
services:
  tomcat:
    build:
      context: 7/tomcat
    image: aursu/centos:tomcat
  centos7web:
    build:
      context: 7/web
    image: aursu/centos:7-web
  centos7node:
    build:
      context: 7/node
    image: aursu/centos:7-node
  centos7uwsgi:
    build:
      context: 7/python2-uwsgi
    image: aursu/centos:7-uwsgi
  centos8web:
    build:
      context: 8/web
    image: aursu/centos:8-web
  centos8httpd:
    build:
      context: 8/httpd
    image: aursu/centos:httpd
