version: "3"
services:
  centos7systemd:
    build:
      context: 7/systemd
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-systemd"
  centos7webdev:
    build:
      context: 7/web
      args:
        centos: $OS7
        image: scm
    image: "aursu/centos:${OS7TAG}-webdev"
  centos7nodedev:
    build:
      context: 7/node/dev
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-nodedev"
  centos7node16dev:
    build:
      context: 7/node-current/dev
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-node16dev"
  centos8systemd:
    build:
      context: 8/systemd
      args:
        centos: $OS8
    image: "aursu/centos:${OS8TAG}-systemd"
  centos8webdev:
    build:
      context: 8/web
      args:
        centos: $OS8
        image: scm
    image: "aursu/centos:${OS8TAG}-webdev"
  centos8nodedev:
    build:
      args:
        centos: $OS8
      context: 8/node/dev
    image: "aursu/centos:${OS8TAG}-nodedev"
  centos8node16dev:
    build:
      args:
        centos: $OS8
      context: 8/node-current/dev
    image: "aursu/centos:${OS8TAG}-node16dev"
  stream8systemd:
    build:
      context: 8-stream/systemd
    image: aursu/centos:stream8-systemd