version: "3"
services:
  tomcat:
    build:
      context: 7/tomcat
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-tomcat"
  centos7web:
    build:
      context: 7/web
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-web"
  centos7node14:
    build:
      context: 7/node14
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-node14"
  centos7node16:
    build:
      context: 7/node16
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-node16"
  stream8web:
    build:
      context: 8-stream/web
    image: aursu/centos:stream8-web
  stream8httpd:
    build:
      context: 8-stream/httpd
      args:
        centos: stream8
    image: aursu/centos:stream8-httpd
  stream8node16:
    build:
      context: 8-stream/node16
      args:
        centos: stream8
    image: aursu/centos:stream8-node16
  stream8node18:
    build:
      context: 8-stream/node18
      args:
        centos: stream8
    image: aursu/centos:stream8-node18
  stream9web:
    build:
      context: 9-stream/web
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-web"
  stream9httpd:
    build:
      context: 9-stream/httpd
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-httpd"
  stream9node16:
    build:
      context: 9-stream/node16
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-node16"
  stream9node18:
    build:
      context: 9-stream/node18
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-node18"