version: "3"
services:
  centos7systemd:
    build:
      context: 7/systemd
    image: aursu/centos:7.7.1908-systemd
  centos7webdev:
    build:
      context: 7/web
      args:
        image: 7.7.1908-scm
    image: aursu/centos:7.7.1908-webdev
  centos7nodedev:
    build:
      context: 7/node/dev
    image: aursu/centos:7-nodedev
  centos8systemd:
    build:
      context: 8/systemd
    image: aursu/centos:8.1.1911-systemd
  centos8webdev:
    build:
      context: 8/web
      args:
        image: 8.1.1911-scm
    image: aursu/centos:8.1.1911-webdev
  centos8nodedev:
    build:
      context: 8/node/dev
    image: aursu/centos:8-nodedev