version: "3"
services:
  centos6curl:
    build:
      context: 6/curl
    image: aursu/centos:6-curl
  centos7base:
    build:
      context: 7/base
    image: aursu/centos:7-base
  centos77base:
    build:
      context: 7/base
      dockerfile: Dockerfile-7.7.1908
    image: aursu/centos:7.7-base
  centos6scm:
    build:
      context: 6/scm
    image: aursu/centos:6-scm
  centos7scm:
    build:
      context: 7/scm
    image: aursu/centos:7-scm
  centos7jdk:
    build:
      context: 7/openjdk/8
    image: aursu/centos:7-jdk-8
