version: "3"
services:
  tomcat:
    build:
      context: 7/tomcat
    image: aursu/centos:7-tomcat
  centos7web:
    build:
      context: 7/web
    image: aursu/centos:7.7.1908-web
  centos7node:
    build:
      context: 7/node
    image: aursu/centos:7.7.1908-node
  centos7uwsgi:
    build:
      context: 7/python2-uwsgi
    image: aursu/centos:7.7.1908-uwsgi
  centos8web:
    build:
      context: 8/web
    image: aursu/centos:8.1.1911-web
  centos8httpd:
    build:
      context: 8/httpd
    image: aursu/centos:8.1.1911-httpd
  centos8node:
    build:
      context: 8/node
    image: aursu/centos:8.1.1911-node
