version: "3"
services:
  tomcat:
    build:
      context: 7/tomcat
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-tomcat"
  centos7web:
    build:
      context: 7/web
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-web"
  centos7node:
    build:
      context: 7/node
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-node"
  centos7node16:
    build:
      context: 7/node-current
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-node16"
  centos8web:
    build:
      context: 8/web
      args:
        centos: $OS8
    image: "aursu/centos:${OS8TAG}-web"
  centos8httpd:
    build:
      context: 8/httpd
      args:
        centos: $OS8
    image: "aursu/centos:${OS8TAG}-httpd"
  centos8node:
    build:
      context: 8/node
      args:
        centos: $OS8
    image: "aursu/centos:${OS8TAG}-node"
  centos8node16:
    build:
      context: 8/node-current
      args:
        centos: $OS8
    image: "aursu/centos:${OS8TAG}-node16"
  stream8web:
    build:
      context: 8-stream/web
    image: aursu/centos:stream8-web