version: "3"
services:
  tomcat:
    build:
      context: 8-rocky/tomcat
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-tomcat"
  rocky8web:
    build:
      context: 8-rocky/web
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-web"
  rocky8nginx:
    build:
      context: 8-rocky/nginx
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-nginx"
  rocky8resty:
    build:
      context: 8-rocky/nginx/resty
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-resty"
  rocky8httpd:
    build:
      context: 8-rocky/httpd
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-httpd"
  rocky8node18:
    build:
      context: 8-rocky/node/18
      args:
        rocky: $RL8
    image: aursu/rockylinux:${RL8TAG}-node18
  rocky8node20:
    build:
      context: 8-rocky/node/20
      args:
        rocky: $RL8
    image: aursu/rockylinux:${RL8TAG}-node20
  rocky8ruby31:
    build:
      context: 8-rocky/ruby/31
      args:
        rocky: $RL8
    image: aursu/rockylinux:${RL8TAG}-ruby31
  rocky9ruby31:
    build:
      context: 9-rocky/ruby/31
      args:
        rocky: $RL9
    image: aursu/rockylinux:${RL9TAG}-ruby31
  rocky9ruby33:
    build:
      context: 9-rocky/ruby/33
      args:
        rocky: $RL9
    image: aursu/rockylinux:${RL9TAG}-ruby33
  stream9web:
    build:
      context: 9-stream/web
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-web"
  stream9httpd:
    build:
      context: 9-stream/httpd
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-httpd"
  stream9node18:
    build:
      context: 9-stream/node/18
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-node18"
  stream9node20:
    build:
      context: 9-stream/node/20
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-node20"
  rocky9web:
    build:
      context: 9-rocky/web
      args:
        rocky: $RL9
    image: "aursu/rockylinux:${RL9TAG}-web"
  rocky9nginx:
    build:
      context: 9-rocky/nginx
      args:
        rocky: $RL9
    image: "aursu/rockylinux:${RL9TAG}-nginx"
  rocky9resty:
    build:
      context: 9-rocky/nginx/resty
      args:
        rocky: $RL9
    image: "aursu/rockylinux:${RL9TAG}-resty"
  rocky9httpd:
    build:
      context: 9-rocky/httpd
      args:
        rocky: $RL9
    image: "aursu/rockylinux:${RL9TAG}-httpd"
  rocky9node18:
    build:
      context: 9-rocky/node/18
      args:
        rocky: $RL9
    image: aursu/rockylinux:${RL9TAG}-node18
  rocky9node20:
    build:
      context: 9-rocky/node/20
      args:
        rocky: $RL9
    image: aursu/rockylinux:${RL9TAG}-node20