version: "3"
services:
  centos7base:
    build:
      context: 7/base
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-base"
  centos7scm:
    build:
      context: 7/scm
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-scm"
  centos7jdk:
    build:
      context: 7/openjdk/8
      args:
        centos: $OS7
    image: "aursu/centos:${OS7TAG}-jdk-8"
  rocky8jdk:
    build:
      context: 8-rocky/openjdk/8
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-jdk-8"
  rocky8base:
    build:
      context: 8-rocky/base
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-base"
  rocky8scm:
    build:
      context: 8-rocky/scm
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-scm"
  stream9jdk:
    build:
      context: 9-stream/openjdk/11
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-jdk-11"
  stream9base:
    build:
      context: 9-stream/base
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-base"
  stream9scm:
    build:
      context: 9-stream/scm
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-scm"