services:
  stream9base:
    build:
      context: 9-stream/base
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-base"
  stream9scm:
    build:
      context: 9-stream/scm
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-scm"
  stream9jdk:
    build:
      context: 9-stream/openjdk/22
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-jdk-22"
