version: "3"
services:
  curl:
    build:
      context: 7/curl
    image: centos:7-curl
  scm:
    build:
      context: 7/scm
    image: centos:7-scm
  httpd:
    build:
      context: httpd
    image: centos:httpd