version: "3"
services:
  stream9puppet7:
    build:
      context: 9-stream/puppet/7
      args:
        centos: $OS9
    privileged: true
    cap_add:
      - SYS_ADMIN
    image: "aursu/centos:${OS9TAG}-puppet7"
  stream9puppet8:
    build:
      context: 9-stream/puppet/8
      args:
        centos: $OS9
    privileged: true
    cap_add:
      - SYS_ADMIN
    image: "aursu/centos:${OS9TAG}-puppet8"
  rocky9puppet8:
    build:
      context: 9-rocky/puppet/8
      args:
        centos: $RL9
    privileged: true
    cap_add:
      - SYS_ADMIN
    image: "aursu/rockylinux:${RL9TAG}-puppet8"
  rocky8docker:
    build:
      context: 8-rocky/docker
      args:
        rocky: $RL8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: aursu/rockylinux:${RL8TAG}-docker-cli
  rocky9docker:
    build:
      context: 9-rocky/docker
      args:
        rocky: $RL9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: aursu/rockylinux:${RL9TAG}-docker-cli