services:
  stream9base:
    build:
      context: base
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-base"
  stream9scm:
    build:
      context: scm
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-scm"
  stream9jdk:
    build:
      context: openjdk/22
      args:
        centos: $OS9
    image: "aursu/centos:${OS9TAG}-jdk-22"
