services:
  stream9puppet7:
    build:
      context: 9-stream/puppet/7
      args:
        centos: $OS9
    privileged: true
    cap_add:
      - SYS_ADMIN
    image: "aursu/centos:${OS9TAG}-puppet7"
  stream9puppet8:
    build:
      context: 9-stream/puppet/8
      args:
        centos: $OS9
    privileged: true
    cap_add:
      - SYS_ADMIN
    image: "aursu/centos:${OS9TAG}-puppet8"
