version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.25

workflows:
  dockercentos:
    jobs:
      - docker-rpmbuild/image:
          name: rocky8base
          compose_file: docker-compose.yml
          build_service: rocky8base
      - docker-rpmbuild/image:
          name: stream9base
          compose_file: docker-compose.yml
          build_service: stream9base
          shorttag: true
      - docker-rpmbuild/image:
          name: rocky8scm
          compose_file: docker-compose.yml
          build_service: rocky8scm
          requires:
            - rocky8base
      - docker-rpmbuild/image:
          name: stream9scm
          compose_file: docker-compose.yml
          build_service: stream9scm
          shorttag: true
          requires:
            - stream9base
      - docker-rpmbuild/image:
          name: rocky8web
          compose_file: docker-compose.web.yml
          build_service: rocky8web
          requires:
            - rocky8base
      - docker-rpmbuild/image:
          name: stream9web
          compose_file: docker-compose.web.yml
          build_service: stream9web
          shorttag: true
          requires:
            - stream9base
      - docker-rpmbuild/image:
          name: rocky8httpd
          compose_file: docker-compose.web.yml
          build_service: rocky8httpd
          requires:
            - rocky8base
      - docker-rpmbuild/image:
          name: stream9httpd
          compose_file: docker-compose.web.yml
          build_service: stream9httpd
          shorttag: true
          requires:
            - stream9base
      - docker-rpmbuild/image:
          name: rocky8jdk
          compose_file: docker-compose.yml
          build_service: rocky8jdk
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: stream9jdk
          compose_file: docker-compose.yml
          build_service: stream9jdk
          requires:
            - stream9scm
      - docker-rpmbuild/image:
          name: rocky8node18
          compose_file: docker-compose.web.yml
          build_service: rocky8node18
          requires:
            - rocky8web
      - docker-rpmbuild/image:
          name: rocky8node20
          compose_file: docker-compose.web.yml
          build_service: rocky8node20
          requires:
            - rocky8web
      - docker-rpmbuild/image:
          name: rocky8systemd
          compose_file: docker-compose.dev.yml
          build_service: rocky8systemd
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: rocky8webdev
          compose_file: docker-compose.dev.yml
          build_service: rocky8webdev
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: stream9node18
          compose_file: docker-compose.web.yml
          build_service: stream9node18
          shorttag: true
          requires:
            - stream9web
      - docker-rpmbuild/image:
          name: stream9node20
          compose_file: docker-compose.web.yml
          build_service: stream9node20
          shorttag: true
          requires:
            - stream9web
      - docker-rpmbuild/image:
          name: stream9systemd
          compose_file: docker-compose.dev.yml
          build_service: stream9systemd
          shorttag: true
          requires:
            - stream9scm
      - docker-rpmbuild/image:
          name: stream9webdev
          compose_file: docker-compose.dev.yml
          build_service: stream9webdev
          shorttag: true
          requires:
            - stream9scm
      - docker-rpmbuild/image:
          name: tomcat
          compose_file: docker-compose.web.yml
          build_service: tomcat
          requires:
            - rocky8jdk
      - docker-rpmbuild/image:
          name: rocky8ruby31
          compose_file: docker-compose.web.yml
          build_service: rocky8ruby31
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: rocky8ruby31puppet
          compose_file: docker-compose.dev.yml
          build_service: rocky8ruby31puppet
          requires:
            - rocky8ruby31
      - docker-rpmbuild/image:
          name: rocky8docker
          compose_file: docker-compose.dev.yml
          build_service: rocky8docker
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: rocky8node18dev
          compose_file: docker-compose.dev.yml
          build_service: rocky8node18dev
          requires:
            - rocky8webdev
      - docker-rpmbuild/image:
          name: rocky8node20dev
          compose_file: docker-compose.dev.yml
          build_service: rocky8node20dev
          requires:
            - rocky8webdev
      - docker-rpmbuild/image:
          name: stream9node18dev
          compose_file: docker-compose.dev.yml
          build_service: stream9node18dev
          shorttag: true
          requires:
            - stream9webdev
      - docker-rpmbuild/image:
          name: stream9node20dev
          compose_file: docker-compose.dev.yml
          build_service: stream9node20dev
          shorttag: true
          requires:
            - stream9webdev