version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build CentOS Docker images
          command: |
            docker-compose build --no-cache
            docker-compose -f docker-compose.web.yml build --no-cache
            docker-compose -f docker-compose.dev.yml build --no-cache
      - run:
          name: Deploy CentOS Docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push aursu/centos:7-base
            docker push aursu/centos:7.7-base
            docker push aursu/centos:7-scm
            docker push aursu/centos:6-curl
            docker push aursu/centos:6-scm
            docker push aursu/centos:7-jdk-8
      - run:
          name: Deploy CentOS Web images
          command: |
            docker push aursu/centos:httpd
            docker push aursu/centos:tomcat
            docker push aursu/centos:7-web
            docker push aursu/centos:7-node
            docker push aursu/centos:7-uwsgi
      - run:
          name: Deploy Centos Development images
          command: |
            docker push aursu/centos:7-systemd
            docker push aursu/centos:circleci
            docker push aursu/centos:7-webdev
            docker push aursu/centos:7-nodedev
