version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.31

workflows:
  dockercentos:
    jobs:
      - docker-rpmbuild/image:
          name: rocky8base
          compose_file: 8-rocky/docker-compose.yml
          build_service: rocky8base
      - docker-rpmbuild/image:
          name: rocky9base
          compose_file: 9-rocky/docker-compose.yml
          build_service: rocky9base
          shorttag: true
      - docker-rpmbuild/image:
          name: stream9base
          compose_file: 9-stream/docker-compose.yml
          build_service: stream9base
          shorttag: true
      - docker-rpmbuild/image:
          name: rocky10base
          compose_file: 10-rocky/docker-compose.yml
          build_service: rocky10base
          shorttag: true
      - docker-rpmbuild/image:
          name: rocky8scm
          compose_file: 8-rocky/docker-compose.yml
          build_service: rocky8scm
          requires:
            - rocky8base
      - docker-rpmbuild/image:
          name: rocky9scm
          compose_file: 9-rocky/docker-compose.yml
          build_service: rocky9scm
          requires:
            - rocky9base
      - docker-rpmbuild/image:
          name: stream9scm
          compose_file: 9-stream/docker-compose.yml
          build_service: stream9scm
          requires:
            - stream9base
      - docker-rpmbuild/image:
          name: rocky10scm
          compose_file: 10-rocky/docker-compose.yml
          build_service: rocky10scm
          requires:
            - rocky10base
      - docker-rpmbuild/image:
          name: rocky8web
          compose_file: 8-rocky/docker-compose.web.yml
          build_service: rocky8web
          requires:
            - rocky8base
      - docker-rpmbuild/image:
          name: rocky9web
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9web
          requires:
            - rocky9base
      - docker-rpmbuild/image:
          name: rocky10web
          compose_file: 10-rocky/docker-compose.web.yml
          build_service: rocky10web
          requires:
            - rocky10base
      - docker-rpmbuild/image:
          name: rocky8nginx
          compose_file: 8-rocky/docker-compose.web.yml
          build_service: rocky8nginx
          requires:
            - rocky8web
      - docker-rpmbuild/image:
          name: rocky9nginx
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9nginx
          requires:
            - rocky9web
      - docker-rpmbuild/image:
          name: rocky8resty
          compose_file: 8-rocky/docker-compose.web.yml
          build_service: rocky8resty
          requires:
            - rocky8nginx
      - docker-rpmbuild/image:
          name: rocky9resty
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9resty
          requires:
            - rocky9nginx
      - docker-rpmbuild/image:
          name: rocky8httpd
          compose_file: 8-rocky/docker-compose.web.yml
          build_service: rocky8httpd
          requires:
            - rocky8base
      - docker-rpmbuild/image:
          name: rocky9httpd
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9httpd
          requires:
            - rocky9base
      - docker-rpmbuild/image:
          name: rocky8jdk
          compose_file: 8-rocky/docker-compose.yml
          build_service: rocky8jdk
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: rocky8jdk21
          compose_file: 8-rocky/docker-compose.yml
          build_service: rocky8jdk21
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: rocky9jdk
          compose_file: 9-rocky/docker-compose.yml
          build_service: rocky9jdk
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky9jdk21
          compose_file: 9-rocky/docker-compose.yml
          build_service: rocky9jdk21
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky8node18
          compose_file: 8-rocky/docker-compose.web.yml
          build_service: rocky8node18
          requires:
            - rocky8web
      - docker-rpmbuild/image:
          name: rocky8node20
          compose_file: 8-rocky/docker-compose.web.yml
          build_service: rocky8node20
          requires:
            - rocky8web
      - docker-rpmbuild/image:
          name: rocky9node20
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9node20
          requires:
            - rocky9web
      - docker-rpmbuild/image:
          name: rocky9node22
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9node22
          requires:
            - rocky9web
      - docker-rpmbuild/image:
          name: rocky10node22
          compose_file: 10-rocky/docker-compose.web.yml
          build_service: rocky10node22
          requires:
            - rocky10web
      - docker-rpmbuild/image:
          name: rocky8systemd
          compose_file: 8-rocky/docker-compose.dev.yml
          build_service: rocky8systemd
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: rocky9systemd
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9systemd
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: stream9systemd
          compose_file: 9-stream/docker-compose.dev.yml
          build_service: stream9systemd
          requires:
            - stream9scm
      - docker-rpmbuild/image:
          name: rocky10systemd
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10systemd
          requires:
            - rocky10scm
      - docker-rpmbuild/image:
          name: rocky8webdev
          compose_file: 8-rocky/docker-compose.dev.yml
          build_service: rocky8webdev
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: rocky9webdev
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9webdev
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky10webdev
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10webdev
          requires:
            - rocky10scm
      - docker-rpmbuild/image:
          name: tomcat
          compose_file: 8-rocky/docker-compose.web.yml
          build_service: tomcat
          requires:
            - rocky8jdk
      - docker-rpmbuild/image:
          name: rocky8ruby31
          compose_file: 8-rocky/docker-compose.web.yml
          build_service: rocky8ruby31
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: rocky9ruby31
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9ruby31
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky9ruby33
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9ruby33
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky8ruby31puppet
          compose_file: 8-rocky/docker-compose.dev.yml
          build_service: rocky8ruby31puppet
          requires:
            - rocky8ruby31
      - docker-rpmbuild/image:
          name: rocky9ruby31puppet
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9ruby31puppet
          requires:
            - rocky9ruby31
      - docker-rpmbuild/image:
          name: rocky9ruby33puppet
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9ruby33puppet
          requires:
            - rocky9ruby33
      - docker-rpmbuild/image:
          name: rocky8docker
          compose_file: 8-rocky/docker-compose.dev.yml
          build_service: rocky8docker
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: rocky9docker
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9docker
          requires:
            - rocky8scm
      - docker-rpmbuild/image:
          name: rocky8node18dev
          compose_file: 8-rocky/docker-compose.dev.yml
          build_service: rocky8node18dev
          requires:
            - rocky8webdev
      - docker-rpmbuild/image:
          name: rocky8node20dev
          compose_file: 8-rocky/docker-compose.dev.yml
          build_service: rocky8node20dev
          requires:
            - rocky8webdev
      - docker-rpmbuild/image:
          name: rocky9node20dev
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9node20dev
          requires:
            - rocky9webdev
      - docker-rpmbuild/image:
          name: rocky9node22dev
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9node22dev
          requires:
            - rocky9webdev
      - docker-rpmbuild/image:
          name: rocky10node22dev
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10node22dev
          requires:
            - rocky10webdev
      - docker-rpmbuild/image:
          name: rocky9python312
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9python312
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky9ansible
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9ansible
          requires:
            - rocky9python312
      - docker-rpmbuild/image:
          name: rocky10python312
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10python312
          requires:
            - rocky10scm
      - docker-rpmbuild/image:
          name: rocky10ansible
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10ansible
          requires:
            - rocky10python312
