version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.15

workflows:
  dockercentos:
    jobs:
      - docker-rpmbuild/image:
          name: centos7base
          compose_file: docker-compose.yml
          build_service: centos7base
      - docker-rpmbuild/image:
          name: stream8base
          compose_file: docker-compose.yml
          build_service: stream8base
      - docker-rpmbuild/image:
          name: stream9base
          compose_file: docker-compose.yml
          build_service: stream9base
          shorttag: true
      - docker-rpmbuild/image:
          name: centos7scm
          compose_file: docker-compose.yml
          build_service: centos7scm
          requires:
            - centos7base
      - docker-rpmbuild/image:
          name: stream8scm
          compose_file: docker-compose.yml
          build_service: stream8scm
          requires:
            - stream8base
      - docker-rpmbuild/image:
          name: stream9scm
          compose_file: docker-compose.yml
          build_service: stream9scm
          shorttag: true
          requires:
            - stream9base
      - docker-rpmbuild/image:
          name: centos7web
          compose_file: docker-compose.web.yml
          build_service: centos7web
          requires:
            - centos7base
      - docker-rpmbuild/image:
          name: stream8web
          compose_file: docker-compose.web.yml
          build_service: stream8web
          requires:
            - stream8base
      - docker-rpmbuild/image:
          name: stream9web
          compose_file: docker-compose.web.yml
          build_service: stream9web
          shorttag: true
          requires:
            - stream9base
      - docker-rpmbuild/image:
          name: stream8httpd
          compose_file: docker-compose.web.yml
          build_service: stream8httpd
          requires:
            - stream8base
      - docker-rpmbuild/image:
          name: stream9httpd
          compose_file: docker-compose.web.yml
          build_service: stream9httpd
          shorttag: true
          requires:
            - stream9base
      - docker-rpmbuild/image:
          name: centos7jdk
          compose_file: docker-compose.yml
          build_service: centos7jdk
          requires:
            - centos7scm
      - docker-rpmbuild/image:
          name: stream8jdk
          compose_file: docker-compose.yml
          build_service: stream8jdk
          requires:
            - stream8scm
      - docker-rpmbuild/image:
          name: stream9jdk
          compose_file: docker-compose.yml
          build_service: stream9jdk
          requires:
            - stream9scm
      - docker-rpmbuild/image:
          name: centos7node14
          compose_file: docker-compose.web.yml
          build_service: centos7node14
          requires:
            - centos7web
      - docker-rpmbuild/image:
          name: centos7node16
          compose_file: docker-compose.web.yml
          build_service: centos7node16
          requires:
            - centos7web
      - docker-rpmbuild/image:
          name: centos7systemd
          compose_file: docker-compose.dev.yml
          build_service: centos7systemd
          requires:
            - centos7scm
      - docker-rpmbuild/image:
          name: centos7webdev
          compose_file: docker-compose.dev.yml
          build_service: centos7webdev
          requires:
            - centos7scm
      - docker-rpmbuild/image:
          name: stream8node16
          compose_file: docker-compose.web.yml
          build_service: stream8node16
          requires:
            - stream8web
      - docker-rpmbuild/image:
          name: stream8node18
          compose_file: docker-compose.web.yml
          build_service: stream8node18
          requires:
            - stream8web
      - docker-rpmbuild/image:
          name: stream8systemd
          compose_file: docker-compose.dev.yml
          build_service: stream8systemd
          requires:
            - stream8scm
      - docker-rpmbuild/image:
          name: stream8webdev
          compose_file: docker-compose.dev.yml
          build_service: stream8webdev
          requires:
            - stream8scm
      - docker-rpmbuild/image:
          name: stream9node16
          compose_file: docker-compose.web.yml
          build_service: stream9node16
          shorttag: true
          requires:
            - stream9web
      - docker-rpmbuild/image:
          name: stream9node18
          compose_file: docker-compose.web.yml
          build_service: stream9node18
          shorttag: true
          requires:
            - stream9web
      - docker-rpmbuild/image:
          name: stream9systemd
          compose_file: docker-compose.dev.yml
          build_service: stream9systemd
          shorttag: true
          requires:
            - stream9scm
      - docker-rpmbuild/image:
          name: stream9webdev
          compose_file: docker-compose.dev.yml
          build_service: stream9webdev
          shorttag: true
          requires:
            - stream9scm
      - docker-rpmbuild/image:
          name: tomcat
          compose_file: docker-compose.web.yml
          build_service: tomcat
          requires:
            - centos7jdk
      - docker-rpmbuild/image:
          name: centos7node14dev
          compose_file: docker-compose.dev.yml
          build_service: centos7node14dev
          requires:
            - centos7webdev
      - docker-rpmbuild/image:
          name: centos7node16dev
          compose_file: docker-compose.dev.yml
          build_service: centos7node16dev
          requires:
            - centos7webdev
      - docker-rpmbuild/image:
          name: stream8node16dev
          compose_file: docker-compose.dev.yml
          build_service: stream8node16dev
          requires:
            - stream8webdev
      - docker-rpmbuild/image:
          name: stream8node18dev
          compose_file: docker-compose.dev.yml
          build_service: stream8node18dev
          requires:
            - stream8webdev
      - docker-rpmbuild/image:
          name: stream9node16dev
          compose_file: docker-compose.dev.yml
          build_service: stream9node16dev
          shorttag: true
          requires:
            - stream9webdev
      - docker-rpmbuild/image:
          name: stream9node18dev
          compose_file: docker-compose.dev.yml
          build_service: stream9node18dev
          shorttag: true
          requires:
            - stream9webdev