version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.31

workflows:
  dockercentos:
    jobs:
      - docker-rpmbuild/image:
          name: rocky8base
          compose_file: 8-rocky/docker-compose.yml
          build_service: rocky8base
          shorttag: true
      - docker-rpmbuild/image:
          name: rocky9base
          compose_file: 9-rocky/docker-compose.yml
          build_service: rocky9base
          shorttag: true
      - docker-rpmbuild/image:
          name: rocky10base
          compose_file: 10-rocky/docker-compose.yml
          build_service: rocky10base
          shorttag: true
      - docker-rpmbuild/image:
          name: rocky9scm
          compose_file: 9-rocky/docker-compose.yml
          build_service: rocky9scm
          requires:
            - rocky9base
      - docker-rpmbuild/image:
          name: rocky10scm
          compose_file: 10-rocky/docker-compose.yml
          build_service: rocky10scm
          requires:
            - rocky10base
      - docker-rpmbuild/image:
          name: rocky9web
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9web
          requires:
            - rocky9base
      - docker-rpmbuild/image:
          name: rocky10web
          compose_file: 10-rocky/docker-compose.web.yml
          build_service: rocky10web
          requires:
            - rocky10base
      - docker-rpmbuild/image:
          name: rocky9nginx
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9nginx
          requires:
            - rocky9web
      - docker-rpmbuild/image:
          name: rocky10nginx
          compose_file: 10-rocky/docker-compose.web.yml
          build_service: rocky10nginx
          requires:
            - rocky10web
      - docker-rpmbuild/image:
          name: rocky9resty
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9resty
          requires:
            - rocky9nginx
      - docker-rpmbuild/image:
          name: rocky10resty
          compose_file: 10-rocky/docker-compose.web.yml
          build_service: rocky10resty
          requires:
            - rocky10nginx
      - docker-rpmbuild/image:
          name: rocky9httpd
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9httpd
          requires:
            - rocky9base
      - docker-rpmbuild/image:
          name: rocky10httpd
          compose_file: 10-rocky/docker-compose.web.yml
          build_service: rocky10httpd
          requires:
            - rocky10base
      - docker-rpmbuild/image:
          name: rocky9jdk
          compose_file: 9-rocky/docker-compose.yml
          build_service: rocky9jdk
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky9jdk21
          compose_file: 9-rocky/docker-compose.yml
          build_service: rocky9jdk21
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky9node20
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9node20
          requires:
            - rocky9web
      - docker-rpmbuild/image:
          name: rocky9node22
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9node22
          requires:
            - rocky9web
      - docker-rpmbuild/image:
          name: rocky10node22
          compose_file: 10-rocky/docker-compose.web.yml
          build_service: rocky10node22
          requires:
            - rocky10web
      - docker-rpmbuild/image:
          name: rocky9systemd
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9systemd
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky10systemd
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10systemd
          requires:
            - rocky10scm
      - docker-rpmbuild/image:
          name: rocky9webdev
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9webdev
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky10webdev
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10webdev
          requires:
            - rocky10scm
      - docker-rpmbuild/image:
          name: rocky9ruby31
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9ruby31
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky9ruby33
          compose_file: 9-rocky/docker-compose.web.yml
          build_service: rocky9ruby33
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky10ruby33
          compose_file: 10-rocky/docker-compose.web.yml
          build_service: rocky10ruby33
          requires:
            - rocky10scm
      - docker-rpmbuild/image:
          name: rocky9ruby31puppet
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9ruby31puppet
          requires:
            - rocky9ruby31
      - docker-rpmbuild/image:
          name: rocky9ruby33puppet
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9ruby33puppet
          requires:
            - rocky9ruby33
      - docker-rpmbuild/image:
          name: rocky10ruby33puppet
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10ruby33puppet
          requires:
            - rocky10ruby33
      - docker-rpmbuild/image:
          name: rocky9docker
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9docker
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky10docker
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10docker
          requires:
            - rocky10scm
      - docker-rpmbuild/image:
          name: rocky9node20dev
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9node20dev
          requires:
            - rocky9webdev
      - docker-rpmbuild/image:
          name: rocky9node22dev
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9node22dev
          requires:
            - rocky9webdev
      - docker-rpmbuild/image:
          name: rocky10node22dev
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10node22dev
          requires:
            - rocky10webdev
      - docker-rpmbuild/image:
          name: rocky9python312
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9python312
          requires:
            - rocky9scm
      - docker-rpmbuild/image:
          name: rocky9ansible
          compose_file: 9-rocky/docker-compose.dev.yml
          build_service: rocky9ansible
          requires:
            - rocky9python312
      - docker-rpmbuild/image:
          name: rocky10python312
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10python312
          requires:
            - rocky10scm
      - docker-rpmbuild/image:
          name: rocky10ansible
          compose_file: 10-rocky/docker-compose.dev.yml
          build_service: rocky10ansible
          requires:
            - rocky10python312
