services:
  rocky9ruby31:
    build:
      context: ruby/31
      args:
        rocky: $RL9
    image: "aursu/rockylinux:${RL9TAG}-ruby31"
  rocky9ruby33:
    build:
      context: ruby/33
      args:
        rocky: $RL9
    image: "aursu/rockylinux:${RL9TAG}-ruby33"
  rocky9web:
    build:
      context: web
      args:
        rocky: $RL9
    image: "ghcr.io/aursu/rockylinux:${RL9TAG}-web"
  rocky9nginx:
    build:
      context: nginx
      args:
        rocky: $RL9
    image: "aursu/rockylinux:${RL9TAG}-nginx"
  rocky9resty:
    build:
      context: nginx/resty
      args:
        rocky: $RL9
    image: "aursu/rockylinux:${RL9TAG}-resty"
  rocky9httpd:
    build:
      context: httpd
      args:
        rocky: $RL9
    image: "aursu/rockylinux:${RL9TAG}-httpd"
  rocky9node20:
    build:
      context: node/20
      args:
        rocky: $RL9
    image: "ghcr.io/aursu/rockylinux:${RL9TAG}-node20"
  rocky9node22:
    build:
      context: node/22
      args:
        rocky: $RL9
    image: "ghcr.io/aursu/rockylinux:${RL9TAG}-node22"