services:
  rocky9docker:
    build:
      context: docker
      args:
        rocky: $RL9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: aursu/rockylinux:${RL9TAG}-docker-cli