services:
  tomcat:
    build:
      context: 8-rocky/tomcat
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-tomcat"
  rocky8web:
    build:
      context: 8-rocky/web
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-web"
  rocky8nginx:
    build:
      context: 8-rocky/nginx
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-nginx"
  rocky8resty:
    build:
      context: 8-rocky/nginx/resty
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-resty"
  rocky8httpd:
    build:
      context: 8-rocky/httpd
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-httpd"
  rocky8node18:
    build:
      context: 8-rocky/node/18
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-node18"
  rocky8node20:
    build:
      context: 8-rocky/node/20
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-node20"
  rocky8ruby31:
    build:
      context: 8-rocky/ruby/31
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-ruby31"
