services:
  rocky8docker:
    build:
      context: docker
      args:
        rocky: $RL8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: aursu/rockylinux:${RL8TAG}-docker-cli