services:
  tomcat:
    build:
      context: tomcat
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-tomcat"
  rocky8web:
    build:
      context: web
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-web"
  rocky8nginx:
    build:
      context: nginx
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-nginx"
  rocky8resty:
    build:
      context: nginx/resty
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-resty"
  rocky8httpd:
    build:
      context: httpd
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-httpd"
  rocky8node18:
    build:
      context: node/18
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-node18"
  rocky8node20:
    build:
      context: node/20
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-node20"
  rocky8ruby31:
    build:
      context: ruby/31
      args:
        rocky: $RL8
    image: "aursu/rockylinux:${RL8TAG}-ruby31"
